"""Added complain table

Revision ID: 485543c154fc
Revises: c6d2d23080c5
Create Date: 2022-11-03 11:14:20.799902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485543c154fc'
down_revision = 'c6d2d23080c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=200), nullable=False),
    sa.Column('complain', sa.Text(length=500), nullable=False),
    sa.Column('date_of_complain', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complain')
    # ### end Alembic commands ###
